language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database IF NOT EXISTS mikron'

script: ./vendor/bin/phpunit .

notifications:
  email: false